project_id = "pkeijxgwxbtxoxnxbqnj"

[functions.seed-admin]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.create-paymongo-source]
verify_jwt = false

[functions.paymongo-webhook]
verify_jwt = false
[functions.notify-vendor]
verify_jwt = false
